# **Kynning á NumPy:**

### Listum breytt í fylki með np.array, útprentun fylkja og eiginleika þeirra

In [51]:
# R1
import numpy as np  # Python forrit sem notar numpy skammstafar það np skv. hefð
v = np.array([0., 2.])
A = np.array([[2., 3., 4.], [4., 5., 6.]])
print('v =', v)
print('A ='); print(A)
print(f'ndim={A.ndim}, shape={A.shape}')

v = [0.000 2.000]
A =
[[2.000 3.000 4.000]
 [4.000 5.000 6.000]]
ndim=2, shape=(2, 3)


**Ath.** Því miður henta f-strengir ekki vel til að prenta út fylki, t.d. er
ekki hægt að tilgreina fjölda aukastafa: ``print(f'A = {A:.3f}')``
gefur villu.

***Æfing:***
1. Prófið ``print('A =', A)`` og líka ``print(f'A =\n{A}')``
2. Prentið líka út `A.size` og `A.dtype`
3. Búið til vigur `x = [3,4,5]` og prentið hann út bæði með print og
   með display. Skoðið x.dtype.
4. Endurtakið lið 3 með `x = [3.,4,5]` (niðurstaðan skýrist af því að
   öll stök NumPy vigurs eru alltaf með sama gagnatag).

### Föll til að búa til fylki

In [60]:
# R2
Z = np.zeros((2,2))   # Hefð að nota stóra stafi fyrir fylki
E = np.ones((2,2))
F = np.full((3,5), 3.14159)
I = np.eye(2)
z = np.zeros(3)       # og litla stafi fyrir vigra
e = np.ones(4)       
k = np.arange(1,11)
h = np.linspace(0,3,7)
print(Z); print(E); print(F); print(I)
print(f'z = {z}, e = {e}'); 
print(f'k = {k}, dtype={k.dtype}')
print(f'h = {h}, dtype={h.dtype}')

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[3.14159 3.14159 3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159 3.14159 3.14159]]
[[1. 0.]
 [0. 1.]]
z = [0. 0. 0.], e = [1. 1. 1. 1.]
k = [ 1  2  3  4  5  6  7  8  9 10], dtype=int64
h = [0.  0.5 1.  1.5 2.  2.5 3. ], dtype=float64


***Æfing:***
1. Stikinn í zeros verður að vera par: Prófið að kalla á ``np.zeros(2,2)``
2. Búið til $2 \times 3$ núllfylki og $3 \times 3$ fylki með 7.5 í öllum sætum.
3. Notið `np.linspace` til að búa til vigurinn $(1, 1.5, 2, 2.5,\ldots, 8)$

### Hægt er að stilla fjölda aukastafa o.fl. í útskrift:

In [3]:
# R3  
np.set_printoptions(precision=2, floatmode='fixed', suppress=True)
A = np.full((3,5), 3.14159)
print('A = '); print(A)

# Stillt aftur á sjálfgefna útskrift:
# np.set_printoptions(precision=8, floatmode='unique', 
#                     suppress=False) # reset to default

A = 
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


***Æfing:***

Keyrið reit R3 og svo reit R2 aftur

### Slembifylki

In [20]:
# R4
import numpy.random as npr
for i in range(4):
    A = npr.random((2,2))  # tekur inn par, gefur 2 x 2 slembifylki
    print(f'i = {i}')
    print(A)

i = 0
[[0.37 0.65]
 [0.10 0.51]]
i = 1
[[0.18 0.04]
 [0.71 0.98]]
i = 2
[[0.83 0.41]
 [0.30 0.58]]
i = 3
[[0.65 0.78]
 [0.68 0.81]]


In [55]:
import numpy as np
b = np.loadtxt('http://cs.hi.is/strei/e.txt', usecols=(0,2,3), delimiter=',').T
b
x = np.array([1,2,3])
x = np.array([(1,2,3),(5,7,9)])
x = np.zeros(3)
x

array([0., 0., 0.])

***Æfing:***

Keyrið reit R4 aftur og aftur

### Vigurreikningar

In [4]:
# R5
import numpy as np
A = np.array([[2., 3.], [4., 5.]])
x = np.array([1,   2,   3  ])
y = np.array([1.0, 1.0, 2.0])
z = x + y          # tilsvarandi stök lögð saman
v = x*x            # tilsvarandi stök margfölduð saman
C = A*A            # - líka í fylkjum
d = x @ x          # innfeldi (skalarmargfeldi)
s = np.sqrt(x)     # tekur kvaðratrót af hverju staki
E = np.exp(A)      # og exp (líka til np.sin, np.log o.s.frv.)
print(z,v,d)       # innfeldið er talan 1*1 + 2*1 + 3*2 = 14
print(f'{C}\n{E}') # \n fer á nýja línu
print(f's={s}')

[2.00 3.00 5.00] [1 4 9] 14
[[ 4.00  9.00]
 [16.00 25.00]]
[[  7.39  20.09]
 [ 54.60 148.41]]
s=[1.00 1.41 1.73]


In [7]:
x = np.array([1,3,4])
np.sum(x), x.sum()

(8, 8)

In [17]:
url = 'http://cs.hi.is/strei/a.txt'  #
A = np.loadtxt(url)
A, A.min(), A.max()
a,b,c = np.loadtxt(url)
print(A)
print(a,b,c)
x,y = np.loadtxt(url).T
print(x,y)

[[1.00 4.00]
 [2.00 5.00]
 [3.00 6.00]]
[1.00 4.00] [2.00 5.00] [3.00 6.00]
[1.00 2.00 3.00] [4.00 5.00 6.00]


In [19]:
ár = np.arange(2015,2019)
p = np.array([2,3,5,7])
I = [False, True, True, False]
J = ár < 2017
print(ár)
print(p[I])
print(p[ár < 2017])
print(J, ár[J], p[J])

[2015 2016 2017 2018]
[3 5]
[2 3]
[ True  True False False] [2015 2016] [2 3]


***Æfing:***

Prófið fleiri aðgerðir (mínus, deilingu, margföldun fylkis og tölu)

In [24]:
#A = npr.random((6,6))
A
B = A[1:4,2:5]
print(A); print(B)

[[0.90 0.39 0.98 0.08 0.57 0.33]
 [0.92 0.74 0.31 0.04 0.85 0.54]
 [0.65 0.47 0.86 0.76 0.33 0.27]
 [0.06 0.18 0.81 0.76 0.25 0.47]
 [0.73 0.93 0.98 0.77 0.97 0.24]
 [0.45 0.47 0.28 0.45 0.17 0.65]]
[[0.31 0.04 0.85]
 [0.86 0.76 0.33]
 [0.81 0.76 0.25]]


In [31]:
import pandas as pd
kosn = pd.read_excel("http://cs.hi.is/t1a/kosningar.xlsx")
#display(kosn)
n = sum(kosn["Atkvæði"])
print(f'n={n}')
kosn["Hlutf"] = kosn["Atkvæði"]/n
# display(kosn)
kosn["Atkv-sætis"] = kosn["Atkvæði"]/kosn["Þingsæti"]
display(kosn.style.format({"Hlutf": "{:.1%}", "Atkv-sætis": "{:.0f}"}))

n=196259


In [ ]:
import pandas as pd
kosn = pd.read_excel("http://cs.hi.is/t1a/kosningar.xlsx")
display(kosn)
n = sum(kosn.Atkvæði)
kosn["Hlutf"] = kosn.Atkvæði/n
display(kosn)